### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by mclaudiopt** [StyraHem/hass#10]
hello
i want to use your amazing addon but i cannot make it work...
i made my configuration but i think i am not receiving the messages / communicating with shelly. what can i do?
thanks

**Comment by hakana** [comment]
How does your network setup look like?

**Comment by mclaudiopt** [comment]
i have just confirmed with supplier of my router...it says it does not support Coap...maybe that is the problem :-(

**Comment by hakana** [comment]
What is the brand and model of the router?

**Comment by mclaudiopt** [comment]
Altice gateway fiberworks
