### ISSUE TITLE
Add devices by IP?

### ISSUE THREAD

**Issue by darookee** [StyraHem/hass#11]
I have all my IoT devices on a different VLAN and currently have no way to forward broadcast traffic between these (the gateway does not have that feature :-( ).
Would it be possible to specify devices by their IP address?

**Comment by hakana** [comment]
All monitor of device status using CoAP (multicast) so if that now work in your setup this component will not work. How do you route between VLANS for other traffic to HASS? Maybe Shelly add http callback later then we will add this.

**Comment by darookee** [comment]
After realizing that it will probably not work and that my HASS.io server does not need to be in the main VLAN I just moved everything IoT to the IoT VLAN. The component is working fine now :-)

**Comment by hakana** [comment]
Great!

**Comment by johntdyer** [comment]
@hakana  -  FWIW I need my Hass.io server to be in my main vlan and my shelly is in my IOS vlan...  Any suggestions as to how I might skip discovery and statically address my shelly devices across vlans ?
