### ISSUE TITLE
Error during setup of component shelly

### ISSUE THREAD

**Issue by N3R1-70** [StyraHem/hass#12]
Hi when I restart home assistant I get this error:
**Error during setup of component shelly**
Error during setup of component shelly
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/shelly/__init__.py", line 104, in setup
    from .pyShelly import pyShelly
ImportError: No module named 'custom_components.shelly.pyShelly'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/setup.py", line 154, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/shelly/__init__.py", line 106, in setup
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined

What am I doing wrong?

My versions are 
- home assistant: 0.91.4
- custom_updater: 4.2.19
- shelly: 0.0.8

Thanks

**Comment by hakana** [comment]
What version of Python do you use?

**Comment by astrandb** [comment]
The log states that …/shelly/init.py contains an error
Please check that the file is named __init__.py i.e. two underscore characters in each end of 'init'

**Comment by N3R1-70** [comment]
1. I have Python 2.7.13
2. The file is **_init_.py**
thanks

**Comment by N3R1-70** [comment]
Sorry from home assistant it tells me that I am using Python version 3.5.3

**Comment by hakana** [comment]
The error you get indicate you running on Python 2. ModuleNotFoundError should be defined in Python 3. You can try replace ModuleNotFoundError to ImportError and see if that helps.

**Comment by N3R1-70** [comment]
Thanks!
How to how do i update to Python 3?

**Comment by N3R1-70** [comment]
I tried... i moved forward but I am getting another error:

>>>>>>>>>>>>>>>>
Error http GET: http://192.168.1.202/color/0 the JSON object must be str, not 'bytes' Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/pyShelly/__init__.py", line 149, in _http_get
    resp_json = json.loads(body)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/pyShelly/__init__.py", line 149, in _http_get
    resp_json = json.loads(body)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
>>>>>>>>>>>>

In addition:
- I have a RGBW2 and it's not working
- I have a shelly 2 set up as a roller and it doesen't work... it sees two channels and not the roller. Also the two channels don't work.

Thanks

**Comment by hakana** [comment]
I have created a new release 0.0.9, please update to this and see if it will work for you.

**Comment by hakana** [comment]
I'm using Python 3.6 and you Python 3.5. I think that the reason you got some errors. I will install Python 3.5 and see if I get the same errors.

**Comment by hakana** [comment]
You can try to change this row:

resp_json = json.loads(body)

to:

resp_json = json.loads(s(body))

In this file:
/srv/homeassistant/lib/python3.5/site-packages/pyShelly/init.py", line 149

**Comment by N3R1-70** [comment]
Thanks. 
Now the cover / roller works. Great.
The Light RGBW2 is not working, actually now it disappeared completely.
It just doesn't see it.
You are doing a great work!

**Comment by hakana** [comment]
Any errors in log?

**Comment by N3R1-70** [comment]
No. No errors.
That's why it's strange.

**Comment by hakana** [comment]
How is it going?

**Comment by pamansari** [comment]
After installing the switches are often showing unavailable

**Comment by N3R1-70** [comment]
Hey! Thanks for your help! It seams to be working, I just did not have time to play with it and make sure everything is working.

**Comment by hakana** [comment]
Great, I will close this issue.
