### ISSUE TITLE
[Feature request] Battery indication

### ISSUE THREAD

**Issue by MADS0LADEN** [StyraHem/hass#15]
Hello, could you add a sensor that keeps track of Shelly H%T's battery levels? :)
Just like wifi_sensor and uptime_sensor in the configuration? 🥇

**Comment by hakana** [comment]
Yes, maybe that is a good idea. Until the you have the battery level as an attribute on the sensor. You can easily do a sensor template if you need it as a sensor. https://www.home-assistant.io/components/template/

**Comment by hakana** [comment]
Battryy sensor have been added to version 0.13
