### ISSUE TITLE
Shelly 1 PM - add temperature and overtemperature sensor

### ISSUE THREAD

**Issue by rufik** [StyraHem/hass#18]
Implement new sensors for Shelly 1 PM, please:
- temperature (float)
- overtemperature (bool)
- overpower (bool)

They are missing right now in component version: 0.0.12/0.0.29. Shelly's status page has them already, example:
```
{
  "time": "09:48",
  "serial": 1,
  "has_update": false,
  [...cut...]
  "relays": [
    {
      "ison": false,
      "has_timer": false,
      "overpower": false
    }
  ],
  "temperature": 37.35,
  "overtemperature": false,
  "update": {
    "status": "idle",
    "has_update": false,
    "new_version": "20190423-080637/v1.4.9-switch1pm-hotfix4@f8c51629",
    "old_version": "20190423-080637/v1.4.9-switch1pm-hotfix4@f8c51629"
  },
  [...cut...]
}
```

**Comment by hakana** [comment]
Thanks for the comment, I will fix it in beginning of next week when I receive all my Shelly 1 PM

**Comment by hakana** [comment]
Temperature attribut and sensor added. Over_temperature and over_power added as attributes on the switch.

**Comment by rufik** [comment]
What about Shelly 2.5? Is your change generic (for all shellies with these sensors) or just for 1 PM only?

**Comment by hakana** [comment]
Generic!
