### ISSUE TITLE
Rename configuration values to match naming of HASS config entries

### ISSUE THREAD

**Issue by tefinger** [StyraHem/hass#2]
I would suggest to rename the configuration values to better match the naming format of other HASS configurations.

So in general it would be:
igmpfix -> igmp_fix
showIdInName -> show_id_in_name
objectIdPrefix -> object_id_prefix
lightSwitch -> light_switch

@hakana What do you think? I know it will break configuration after upgrading to new version but as this component has just been released a few days ago the pain wouldn't be that much :-)

**Comment by hakana** [comment]
I will change this in next release, I changed object_id_prefix to only id_prefix.

**Comment by tefinger** [comment]
If you want to you can assign it to me and I will do it.

**Comment by hakana** [comment]
Already done ;)

**Comment by tefinger** [comment]
Alright :-)

**Comment by mclaudiopt** [comment]
hi there
on your example   discover: should be discovery:  can you please correct?
also it gives me error using name and lightswitch

**Comment by hakana** [comment]
Thanks, i have fixed that in the examples.

Can you post your config of shelly. In the latest release we shanged it to light_switch

**Comment by mclaudiopt** [comment]
well i cannot make it work since all variables given me error

**Comment by tefinger** [comment]
@mclaudiopt pls post your config and error message from log here. Otherwise it is really hard to find out what's the problem.

**Comment by mclaudiopt** [comment]
config:
`
shelly:
  discovery: true
  #devices:      #devices to be added
     - id: 93A775
       light_switch: true
       name: 'Luz da sala'   #set friendly name
``

`error:


Invalid config for [shelly]: [light_switch] is an invalid option for [shelly]. Check: shelly->shelly->devices->0->light_switch. (See /config/configuration.yaml, line 32). Please check the docs at https://home-assistant.io/components/shelly/

**Comment by tefinger** [comment]
@mclaudiopt Try like this:

```
shelly:
  discovery: true
  devices:
    - id: 93A775
      light_switch: true
      name: 'Luz da sala'
```

**Comment by mclaudiopt** [comment]
still same error
Invalid config for [shelly]: [light_switch] is an invalid option for [shelly]. Check: shelly->shelly->devices->0->light_switch. (See /config/configuration.yaml, line 32). Please check the docs at https://home-assistant.io/components/shelly/

**Comment by mclaudiopt** [comment]
added # to light_switch to avoid the error, but even after reboot nothing happens.
there is no way to avoid indicating the device id and auto discovery to work?

**Comment by tefinger** [comment]
Are you sure you have the latest version 0.0.5 installed?
`light_switch` is available since 0.0.5 - before it was called `lightSwitch`

**Comment by mclaudiopt** [comment]
yes.
if i change to lightswitch same error
![image](https://user-images.githubusercontent.com/48178294/55583158-22bb2600-5719-11e9-9f3a-4eeba6b16363.png)

**Comment by tefinger** [comment]
Please not the uppercase `S` in `lightSwitch`

**Comment by mclaudiopt** [comment]
its not uppercased

**Comment by tefinger** [comment]
But it should be (if you are using a version < 0.0.5)

**Comment by mclaudiopt** [comment]
how do i know wich version i have?

**Comment by mclaudiopt** [comment]
i just downloaded from the site...

**Comment by tefinger** [comment]
You can check file `config/custom_components/shelly/__init__.py` and search for a line like this `__version = "0.0.5"`

**Comment by mclaudiopt** [comment]
you are right. i changed from s to S and config was OK. rebooting now.
where i can download latest version? can it update automatically ?
can it autodiscover the devices without indicating the id?

thanks a lot for your help !

**Comment by mclaudiopt** [comment]
you are right. i am with 0.0.4. where can i download

**Comment by tefinger** [comment]
You can use [custom_updater](https://github.com/custom-components/custom_updater) for updating the component:
```
custom_updater:
  component_urls:
    - https://raw.githubusercontent.com/StyraHem/hass/master/custom_updater.json
```

You don't have to specify the device ids in the configuration. Only if you need to change the name or type (light instead of switch) for a device. Discovery is enabled by default and new detected devices will be added to HA automatically.

**Comment by mclaudiopt** [comment]
so it means that only like this:
shelly:
  discovery: true

it will create identifies, right?

**Comment by tefinger** [comment]
Yeah. But `discovery` is `true` by default so it is enough to add `shelly:` to `configuration.yaml`

**Comment by mclaudiopt** [comment]
thanks...
in my case no entities are beeing added :-(

**Comment by mclaudiopt** [comment]
hi there
so 

network:
i use my PI directly connected to my router and dont have any problem
log file:

2019-04-05 09:08:50 ERROR (SyncWorker_0) [homeassistant.util.yaml] YAML file 
2019-04-05 09:08:51 WARNING (MainThread) [homeassistant.loader] You are using a custom component for custom_updater which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-04-05 09:08:54 WARNING (MainThread) [homeassistant.loader] You are using a custom component for shelly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.


regarding the code:
if i use this it works without any problems:
switch:
  - platform: rest
    name: "Luz Sala de jantar"
    scan_interval: 5
    resource: http://192.168.1.94/relay/0
    body_on: 'turn=on'
    body_off: 'turn=off'
    is_on_template: '{{ value_json.ison == true}}'
    headers:
      content-type: application/x-www-form-urlencoded
  - platform: rest
    name: "Luz Cozinha"
    scan_interval: 5
    resource: http://192.168.1.95/relay/0
    body_on: 'turn=on'
    body_off: 'turn=off'
    is_on_template: '{{ value_json.ison == true}}'
  - platform: rest
    name: "Luz Quarto da Maria"
    scan_interval: 5
    resource: http://192.168.1.96/relay/0
    body_on: 'turn=on'
    body_off: 'turn=off'
    is_on_template: '{{ value_json.ison == true}}'
  - platform: rest
    name: "Luz Sala da Cave"
    scan_interval: 5
    resource: http://192.168.1.110/relay/0
    body_on: 'turn=on'
    body_off: 'turn=off'
    is_on_template: '{{ value_json.ison == true}}'
  - platform: mqtt
    name: "Toalheiro WC Visitas"
    state_topic: "stat/TomadaWCRC/POWER"
    command_topic: "cmnd/TomadaWCRC/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
  - platform: mqtt
    name: "Toalheiro WC Suite"
    state_topic: "stat/BK21quarto/POWER"
    command_topic: "cmnd/BK21quarto/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
  - platform: mqtt
    name: "Toalheiro WC 1a"
    state_topic: "stat/BK22_1a/POWER"
    command_topic: "cmnd/BK22_1a/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    retain: false

**Comment by hakana** [comment]
We using CoAP for detecting devices. CoAP using multicast 224.0.1.187 over UDP port 5683.
If you have a firewall on your Raspberry PI you have to open this port.

Can you run `tcpdump port 5683` and see if you got any CoAP messages from your Shellies.

**Comment by mclaudiopt** [comment]
hi there...
how can i do tcpdump? on the pi itself you mean?
where to open the port? in the router? i dont have firewall on the pi

**Comment by hakana** [comment]
If you don't have the firewall in your Raspberry Pi that is not the issue. You don't have to open any ports in you router.

Info on tcpdump on HASSIO:
https://community.home-assistant.io/t/is-there-a-tcpdump-addon-for-hassio/44847

**Comment by mclaudiopt** [comment]
hi here is the result
![image](https://user-images.githubusercontent.com/48178294/55647919-d3d3c600-57d6-11e9-8cd6-e42990610c9e.png)

**Comment by hakana** [comment]
Of some reson you don't receive the UDP messages to your Raspberry PI. How is your network look like. Do you have a separate AP or using WiFi with your router? What model of router do you have?

**Comment by hakana** [comment]
Do you have more than one network interface on your RPI?

**Comment by mclaudiopt** [comment]
hello
i dont have other AP...
so my PI is connected by RJ45 to my router, then i have wifi connecting to the shelly's
my router is from my operator network...

**Comment by hakana** [comment]
What model of router?

**Comment by mclaudiopt** [comment]
http://www.alticelabs.com/en/286-altice-labs-developed-a-new-fiber-gateway-4x4.html

**Comment by philklei** [comment]
How to do it in docker? 
i created hass on my synology with docker ... 
network was bridged ...

**Comment by hakana** [comment]
> How to do it in docker?
> i created hass on my synology with docker ...
> network was bridged ...

I running it on Hass.IO under docker and it working out of the box for me.
