### ISSUE TITLE
Change file name to custom_updater.json

### ISSUE THREAD

**Issue by astrandb** [StyraHem/hass#3]
I suggest that you rename customer_updater.json to custom_updater.json. It is a breaking change for those that use the feature but it better to do it now when the component is newborn.

**Comment by hakana** [comment]
Thanks, I have changed the name now!

Do you know how to add it to custom updater official list? https://raw.githubusercontent.com/custom-components/information/master/repos.json

**Comment by tefinger** [comment]
@hakana https://github.com/custom-components/information#want-access-to-push-your-amazing-stuff-to-this-space I think you have to contact the owner of the custom-components organization

**Comment by mclaudiopt** [comment]
that would be great !

**Comment by hakana** [comment]
I think this is what we need to do, but right now I don't have time to check this out. And if we get it into Home Assistant components we don't need it I think.

These lists are autogenerated by https://github.com/ludeeus/customjson, developers are welcome to add their elements to that tool, the default lists are updated once every hour, and this component checks it on startup, once every day and when you use the service custom_updater.check_all or click the CHECK button if you are using the tracker-card.

**Comment by mclaudiopt** [comment]
it works ! great job !
![image](https://user-images.githubusercontent.com/48178294/55585371-65333180-571e-11e9-9cd7-9263e92b4fa6.png)

**Comment by hakana** [comment]
@mclaudiopt  Thanks and great!
