### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by mclaudiopt** [StyraHem/hass#4]
it would be great do be able to configure automation directly on HA :-)

**Comment by hakana** [comment]
I don't understand, please explain more ;)

**Comment by mclaudiopt** [comment]
for example to be able to configura hours to switch on and off without need of HA automations ....

**Comment by astrandb** [comment]
I think that would be the wrong way to go. Either you use the built in functions in the Shelly devices and the Shelly app or you use HA to handle scenes, automations etc. I don’t see a use case for a mixup of both worlds.

**Comment by hakana** [comment]
@astrandb I agree with you, this will not be a new GUI for the Shellies just connect it to HASS. You can get the ip address of the device in HASS and then easy configure it in the web browser. If you want it in HASS you can create a iFrame and show it there.

[Image of iFrame](https://photos.app.goo.gl/kdZiBGj5nPmzLbxu8)
