### ISSUE TITLE
Set roller/cover position by percentage

### ISSUE THREAD

**Issue by tefinger** [StyraHem/hass#8]
Currently the cover only supports moving up or down. It would be nice if it also allows setting the position to a percentage value.

**Comment by hakana** [comment]
That should be implemented. Can you see the position?

**Comment by tefinger** [comment]
I think it is implemented in pyShelly but not in Shelly cover platform - see:
```
    def set_cover_position(self, **kwargs):
        """Move the cover to a specific position."""
        pass
```

**Comment by hakana** [comment]
You are right! I will fix that.

**Comment by hakana** [comment]
Done, 0.0.7
